### ISSUE TITLE
Error while rendering component

### ISSUE THREAD

**Issue by anshumanv** [jackrzhang/react-pokemon-gif#1]
Hey, this component is amazing.

I tried using it in my app and getting this error - 

![image](https://user-images.githubusercontent.com/21009455/34860154-a218795a-f781-11e7-893c-ae5b1cf0b754.png)

Any leads?

**Comment by Lisser** [comment]
Same issue here.. Did you manage to get it working?

**Comment by anshumanv** [comment]
I needed it urgently so I created one here - https://github.com/anshumanv/react-poke-sprites with due credits to the original component. @Lisser

**Comment by Lisser** [comment]
Wicked thanks!

**Comment by anshumanv** [comment]
Do let me know if it works well! :smile:

**Comment by jackrzhang** [comment]
I'm deprecating this package. I've added a note to the README to direct people to @anshumanv's work with [`react-poke-sprites`](https://github.com/anshumanv/react-poke-sprites).

**Comment by anshumanv** [comment]
Appreciate it @jackrzhang! :smile: 
I'll keep it actively maintained.
